defaults:
  - _self_
  - agent: collector
  - envs: endless_all
  - agent/obs_configs: camera
actors:
  hero:
    agent: collector
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
ev_id: hero
carla_sh_path: /mnt/data/carla/0.9.16/CARLA_0.9.16/CarlaUE4.sh
kill_running: true
